### ISSUE TITLE
Remove 2 from the name

### ISSUE THREAD

**Issue by benmccann** [play2-maven-plugin/play2-maven-plugin#145]
The next version of Play is going to be Play 3. This plugin should still work with future versions of Play, so it's going to be confusing to have "2" in the name

**Comment by gslowikowski** [comment]
I thought about it, but I don't know if this is a good idea, because:
- I don't know if now (in beta phase) is the proper moment to do it, maybe this is something better suitable for version `2.0`
- I don't know, how different will Play! v3 be compared to v2; maybe it would be better to create separate plugin; maybe you will add Maven support to it (as documented somewhere)

Generally, I don't know, what be the future of Play! Framework (starting from version `3.0`) and my plugin. I don't want to make troubles to plugin's users and force them to update their projects, CI builds, etc. right now without really good reason.

**Comment by benmccann** [comment]
Play 3 will not be significantly different from Play 2. Play is switching to semantic versioning after 2.6. So instead of 2.2, 2.4, 2.6, etc. the next versions will be 3, 4, 5, etc.

**Comment by gmethvin** [comment]
We want maven support in Play 3, and ideally for future versions of 2.x, so the big question here is whether to use this plugin (and perhaps modify it), write our own based on the Lagom plugin, or some combination of those things.

**Comment by gslowikowski** [comment]
@gmethvin if this plugin would be incorporated into Play! Framework tools family, it would require some changes like `groupId` change or move to `typesafe` organization. This means it would be a new plugin, a result of migration of this one or combination of it and a Lagon one. Anyway, there is no reason to change packaging here.

**Comment by gslowikowski** [comment]
I'm closing it now. Reopen if you will want to discuss it further.
