### ISSUE TITLE
Ebean Enhance with custom confDirectory location.

### ISSUE THREAD

**Issue by Bangalor** [play2-maven-plugin/play2-maven-plugin#150]
I've changed my confDirectory localtion in plugin configuration. ebean-enhance is seems have broken. It still looking for ${basedir}/conf/application.conf.
Play2EbeanEnhanceMojo should resolve application.conf file relative to confDirectory.

**Comment by gslowikowski** [comment]
Thank you for your report.

Actually you found inconsistency in configuration.
[confDirectory](https://github.com/play2-maven-plugin/play2-maven-plugin/blob/play2-1.0.0-rc1/play2-maven-plugin/src/main/java/com/google/code/play2/plugin/Play2RoutesCompileMojo.java#L64) parameter was introduced long time ago (issue #22) and is used only by `routes-compile` mojo to find router files (not `application.conf` file).

`ebean-enhance` mojo uses two system properties [config.resource and config.file](https://github.com/play2-maven-plugin/play2-maven-plugin/blob/play2-1.0.0-rc1/play2-maven-plugin/src/main/java/com/google/code/play2/plugin/Play2EbeanEnhanceMojo.java#L169-L179) to configure configuration file location.

Things are complicated because Ebean related logic was changing over time and was different for different Play! Framework versions. Since this plugin supports many versions, I would like it to behave like SBT behaves for every Play! version.

The simple solution would be to add `confDirectory` parameter to `ebean-ehnance` mojo, but I cannot guarantee this will be ultimate solution.

For now you have to run Maven with `-Dconfig.file=configfilepath` or `-Dconfig.resource=configresourcename`.

Could you create simple test project? I'm curious, how exactly your project looks like.

**Comment by Bangalor** [comment]
I tried to save standard maven folder structure in my project. I've placed conf directory to src/main/resources and changed path to directory through confDirectory.

**Comment by Bangalor** [comment]
While creating play module i've found one more issue. ebean-enhance resolves classes to enhance only from application.conf not reference.conf.
Ebean-enhance should resolve package to enhance not only from application.conf but reference.conf too.
Currently i am using -Dconfig.file as workaround.

**Comment by gslowikowski** [comment]
Issue fixed by #162 

New `1.0.0-rc3-SNAPSHOT` snapshot deployed, can you test please.

New implementation supports `reference.conf` files. There is no need to use `config.file` or `config.resource` system parameters if `application.conf` (or `reference.conf`) file is located in resources directory (it doesn't have to be `conf` directory).

**Comment by Bangalor** [comment]
With 1.0.0-rc3-SNAPSHOT everything is working fine. Thanks!

**Comment by gslowikowski** [comment]
Thank you for testing.

I've publish some of my tests projects for this issue [here](https://github.com/play2-maven-plugin/play2-maven-plugin/issues/150). Will cut 1.0.0-rc3 release soon.
