### ISSUE TITLE
Support .tar.gz Dist Packaging

### ISSUE THREAD

**Issue by vjkoskela** [play2-maven-plugin/play2-maven-plugin#88]
The PlayFramework and your plugin both provide the dist goal which creates a zip file containing the entire application, dependencies and scripts. However, zip files drop permissions. When building Play Framework applications "natively" you can lean on SBT to build a .tar.gz for you that has the same contents as the zip produced by dist. As described here:

https://www.playframework.com/documentation/2.4.x/Production

Maven can also produce .tar.gz assemblies the trick of course is ensuring the same manifest is included as defined by the dist goal. Is there a way to produce a .tar.gz without redefining the manifest? If not, would it be possible to get a dist-tar-gz (or some such) target added in a future release?

**Comment by gslowikowski** [comment]
Maven `play2:dist` task archive is very primitive. I will take a look at this issue later.

I would advise you to use [Maven Assembly Plugin](http://maven.apache.org/plugins/maven-assembly-plugin/) instead. Maven assemblies are very powerful.

Using separate, specialized plugin for distribution archive generation in Maven is similar to SBT. SBT delegates this task to [SBT Native Packager](https://github.com/sbt/sbt-native-packager). There is one important difference -  Play Framework SBT Plugin preconfigures SBT Native Packager Plugin. In Maven plugins generally do not cooperate with each other, so you have to prepare the assembly descriptor yourself. Maybe I will prepare separate documentation page about this.

**Comment by ptrivedi9400** [comment]
I understand that there are few ways to create tar.gz and it reduces the requirement of having such goal. Just curious but since we have zip structure why can't we have tar.gz. it is just another version of the zipping structure. what prevents anyone to duplicate existing zip code plugin class and convert it to tar.gz.

**Comment by gslowikowski** [comment]
Sorry for not responding so long.

I read some documentation:
- [about Maven Assembly Plugin](http://maven.apache.org/plugins/maven-assembly-plugin/)
- [especially about Maven assembly descriptor](http://maven.apache.org/plugins/maven-assembly-plugin/assembly.html)
- [about Play! dist task](https://www.playframework.com/documentation/2.5.x/Deploying#Using-the-dist-task)
- [about SBT Native Packager from Play! PoV](https://www.playframework.com/documentation/2.5.x/Deploying#the-native-packager)
- [about Universal packaging in SBT Native Packager](http://www.scala-sbt.org/sbt-native-packager/formats/universal.html)
- [about Play! packaging from SBT Native Packager PoV](http://www.scala-sbt.org/sbt-native-packager/recipes/play.html)

The conclusions are:
- in Maven Assembly Plugin multiple distribution formats can be configured and the plugin will generate multiple output archives in one pass, see `formats` documentation [here](http://maven.apache.org/plugins/maven-assembly-plugin/assembly.html),
- in SBT `dist` task only one file can be generated, by default it's `zip` file (see [source line](https://github.com/sbt/sbt-native-packager/blob/v1.0.3/src/main/scala/com/typesafe/sbt/packager/universal/UniversalPlugin.scala#L84)), you can change it in your build, e.g.:
```scala
dist <<= packageZipTarball in Universal
```
generates `tgz` file instead of `zip`.

I think the simplest solution will be to add `distFormat` parameter do `play2:dist` mojo.
I will have to check, what formats we should support (not all formats used by Maven Assembly Plugin make sense - `war` and `dir` are supported by different mojos). Didn't find simple method to determine file extension per packaging format too. It would be good if archivers could provide them, but I don't see it in the sources of [Plexus archivers](https://github.com/codehaus-plexus/plexus-archiver/tree/master/src/main/java/org/codehaus/plexus/archiver). I will have to analyze, how Maven Assembly Plugin processes the list of formats.

Write, which for you need, please.

**Comment by ptrivedi9400** [comment]
@gslowikowski I think you solution is much cleaner and better. lets discuss more on that. let me close my PR as it was like patch to someone who wants to do tar against some kind of unique solution.

**Comment by gslowikowski** [comment]
I've started working on this issue and found that zip files can preserve file permissions. This feature is supported by [Apache Commons Compress](https://commons.apache.org/proper/commons-compress/) library used internally by both [SBT Native Packager](https://github.com/sbt/sbt-native-packager) and [Plexus Archiver](http://codehaus-plexus.github.io/plexus-archiver/index.html) (used by [Maven Assembly Plugin](http://maven.apache.org/plugins/maven-assembly-plugin/)).

I will create two separate issues for:
- setting executable permission for Unix script,
- supporting different archive formats.

**Comment by ptrivedi9400** [comment]
@gslowikowski this is great. this will make the plugin more generic.

**Comment by gslowikowski** [comment]
#127 and #128 done, test it please.
